-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg9uhIRanvMmplma+o
iCnjmuft/NxenJCGIHgHvyNMPx+gCgYIKoZIzj0DAQehRANCAARgz6KAkBw7X9T8
y9tYWYkGQN+WU6Wyg/kgbeVTTcdj7r5jFirMclbQkfO4ZdL/nX3ixIjxXzd52wbX
al5nMiZU
-----END PRIVATE KEY-----